# Generated by Django 2.0.4 on 2018-05-28 17:28

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShutongUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名称')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='电话')),
                ('dept', models.IntegerField(default=0, verbose_name='部门')),
                ('is_active', models.BooleanField(default=True, verbose_name='己激活')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('is_staff', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='己删除')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShutongDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='己删除')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('parent', models.IntegerField(default=0, verbose_name='上级部门')),
                ('leader', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门负责人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShutongRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='己删除')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='角色描述')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='ShutongUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='己删除')),
                ('user', models.IntegerField(verbose_name='用户')),
                ('role', models.IntegerField(verbose_name='角色')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
